version: '3.9'

services:
  db:
    image: mysql:5.7
    platform: linux/amd64
    environment:
    - MYSQL_DATABASE=flask_db
    - MYSQL_ROOT_PASSWORD=root
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
    ports:
      - 3306:3306